// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiviFzdjCzgcTgffkVlFhilW6ca1oGN40',
    appId: '1:358505628191:web:eaa0945cb7d85e15210b2a',
    messagingSenderId: '358505628191',
    projectId: 'geosense-657ae',
    authDomain: 'geosense-657ae.firebaseapp.com',
    storageBucket: 'geosense-657ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkt0c0EzolLbKLIVFXKHwbZ8eUUC3OEoQ',
    appId: '1:358505628191:android:06ab692b5fe339b7210b2a',
    messagingSenderId: '358505628191',
    projectId: 'geosense-657ae',
    storageBucket: 'geosense-657ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8h-HM3lPli-bBWjEp7ot6_Qs1VsRJwE',
    appId: '1:358505628191:ios:fd52fa1363cacf8f210b2a',
    messagingSenderId: '358505628191',
    projectId: 'geosense-657ae',
    storageBucket: 'geosense-657ae.appspot.com',
    iosClientId: '358505628191-86iittn9ev9pmbvshal3gfj560lojo23.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8h-HM3lPli-bBWjEp7ot6_Qs1VsRJwE',
    appId: '1:358505628191:ios:fd52fa1363cacf8f210b2a',
    messagingSenderId: '358505628191',
    projectId: 'geosense-657ae',
    storageBucket: 'geosense-657ae.appspot.com',
    iosClientId: '358505628191-86iittn9ev9pmbvshal3gfj560lojo23.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );
}
